name: Compile Fritzing
on:
  release:
    types:
      - created
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write
  packages: write

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: TheMrMilchmann/setup-msvc-dev@v3.0.0
        with:
          arch: x64
      - run: tools/release_fritzing.bat
        shell: cmd
