name: Compile Fritzing
on:
  release:
    types:
      - created
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write
  packages: write

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4.1.1
