name: Compile Fritzing
on:
  release:
    types:
      - created
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write
  packages: write

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: TheMrMilchmann/setup-msvc-dev@v3.0.0
        with:
          arch: x64
      - uses: jurplel/install-qt-action@v3.3.0
      - run: tools/release_fritzing.bat 0.10 64 2022
        shell: cmd
        env:
          QTBIN: "D:\\a\\fritzing-app\\Qt\\5.15.2\\msvc2019_64\\bin"
